CREATE TABLE IF NOT EXISTS Category(id INTEGER PRIMARY KEY AUTOINCREMENT,CategoryName TEXT);
-- INSERT or IGNORE INTO Category VALUES (1, 'Start up');
-- INSERT or IGNORE INTO Category VALUES (2, 'Programming');
 
CREATE TABLE IF NOT EXISTS MyWebsite(id INTEGER PRIMARY KEY AUTOINCREMENT, myWebId INTEGER, websiteName TEXT, [url] TEXT);
-- INSERT or IGNORE INTO MyWebsite(id, myWebId, websiteName, [url]) VALUES (1, 1, 'Amazon', 'https://amazon.com');
-- INSERT or IGNORE INTO MyWebsite(id, myWebId, websiteName, [url]) VALUES (2, 1, 'Reddit', 'https://reddit.com');
-- INSERT or IGNORE INTO MyWebsite(id, myWebId, websiteName, [url]) VALUES (3, 2, 'Stackoverflow', 'https://stackoverflow.com');
-- INSERT or IGNORE INTO MyWebsite(id, myWebId, websiteName, [url]) VALUES (4, 2, 'Educative io', 'https://educative.io');
-- INSERT or IGNORE INTO MyWebsite(id, myWebId, websiteName, [url]) VALUES (5, 2, 'Cloudinary', 'https://cloudinary.com');

CREATE TABLE IF NOT EXISTS Bookmarks(id INTEGER PRIMARY KEY AUTOINCREMENT, pageTitle TEXT, pageUrl TEXT);
-- INSERT or IGNORE INTO Bookmarks VALUES (1, 'Test Bookmark', "https://google.com");

CREATE TABLE IF NOT EXISTS OfferAds(id INTEGER PRIMARY KEY AUTOINCREMENT,OfferName TEXT, OfferImgURL TEXT, URLDest TEXT);
INSERT or IGNORE INTO OfferAds VALUES (1, 'Affiliate 1', 'https://raw.githubusercontent.com/lateef10/OtherWebOrg/master/offer1.jpg', 'https://ebay.com');
INSERT or IGNORE INTO OfferAds VALUES (2, 'Affiliate 2', 'https://raw.githubusercontent.com/lateef10/OtherWebOrg/master/offer2.jpg', 'https://amazon.com');
INSERT or IGNORE INTO OfferAds VALUES (3, 'Affiliate 3', 'https://raw.githubusercontent.com/lateef10/OtherWebOrg/master/offer3.jpg', 'https://aliexpress.com');



CREATE TABLE IF NOT EXISTS AllWebsite(id INTEGER PRIMARY KEY AUTOINCREMENT, CatId INTEGER, CatName TEXT, WebsiteName TEXT, WebsiteURL TEXT, ImageURL TEXT);
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (1, 1, 'Shopping', 'Amazon', 'https://amazon.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.amazon.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (2, 1, 'Shopping', 'Walmart', 'https://walmart.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.walmart.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (3, 1, 'Shopping', 'Ebay', 'https://ebay.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.ebay.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (4, 1, 'Shopping', 'World Market', 'https://worldmarket.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.worldmarket.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (5, 1, 'Shopping', 'Target', 'https://target.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.target.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (6, 1, 'Shopping', 'Home Depot', 'https://homedepot.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.homedepot.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (7, 1, 'Shopping', 'Best Buy', 'https://bestbuy.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.bestbuy.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (8, 1, 'Shopping', 'Aliexpress', 'https://aliexpress.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.aliexpress.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (9, 1, 'Shopping', 'Kohls', 'https://kohls.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.kohls.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (10, 1, 'Shopping', '4moms', 'https://4moms.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.4moms.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (11, 1, 'Shopping', 'Flipkart', 'https://flipkart.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.flipkart.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (12, 1, 'Shopping', 'Overstock', 'https://overstock.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.overstock.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (13, 1, 'Shopping', 'QVC', 'https://qvc.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.qvc.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (14, 1, 'Shopping', 'Lehmans', 'https://lehmans.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.lehmans.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (15, 1, 'Shopping', 'Noon', 'https://noon.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.noon.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (16, 1, 'Shopping', 'Souq', 'https://saudi.souq.com', 'https://raw.githubusercontent.com/lateef10/OtherWebOrg/master/AllWeb/souq.png');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (17, 1, 'Shopping', 'Lowes', 'https://lowes.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.lowes.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (18, 1, 'Shopping', 'Kmart', 'https://kmart.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.kmart.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (19, 1, 'Shopping', 'Burkes', 'https://burkesoutlet.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.burkesoutlet.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (20, 1, 'Shopping', 'Breville', 'https://breville.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.breville.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (21, 1, 'Shopping', 'Inspire Uplift', 'https://inspireuplift.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.inspireuplift.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (22, 1, 'Shopping', 'Koleimports', 'https://koleimports.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.koleimports.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (23, 1, 'Shopping', 'Maisonette', 'https://maisonette.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.maisonette.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (24, 1, 'Shopping', 'Boxed', 'https://boxed.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.boxed.com/');

INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (25, 2, 'News', 'CNN', 'https://cnn.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.cnn.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (26, 2, 'News', 'Fox News', 'https://foxnews.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.foxnews.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (27, 2, 'News', 'Reuters', 'https://mobile.reuters.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.reuters.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (28, 2, 'News', 'BBC', 'https://bbc.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.bbc.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (29, 2, 'News', 'Sky Sports', 'https://skysports.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.skysports.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (30, 2, 'News', 'Yahoo News', 'https://yahoo.com/news/', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.yahoo.com/news/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (31, 2, 'News', 'WSJ', 'https://wsj.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.wsj.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (32, 2, 'News', 'NBC', 'https://nbcnews.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.nbcnews.com/');

INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (33, 3, 'Beauty & Accessories', 'MAC', 'https://maccosmetics.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.maccosmetics.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (34, 3, 'Beauty & Accessories', 'Sephora', 'https://sephora.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.sephora.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (35, 3, 'Beauty & Accessories', 'Chanel', 'https://chanel.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.chanel.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (36, 3, 'Beauty & Accessories', 'Bareminerals', 'https://bareminerals.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.bareminerals.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (37, 3, 'Beauty & Accessories', 'Milani', 'https://milanicosmetics.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.milanicosmetics.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (38, 3, 'Beauty & Accessories', 'Dior', 'https://dior.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.dior.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (39, 3, 'Beauty & Accessories', 'Beautycounter', 'https://beautycounter.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.beautycounter.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (40, 3, 'Beauty & Accessories', 'Aveda', 'https://aveda.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.aveda.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (41, 3, 'Beauty & Accessories', 'Barielle', 'https://barielle.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.barielle.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (42, 3, 'Beauty & Accessories', 'Olay', 'https://olay.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.olay.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (43, 3, 'Beauty & Accessories', 'Caudalie', 'https://us.caudalie.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.caudalie.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (44, 3, 'Beauty & Accessories', 'Limecrime', 'https://limecrime.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.limecrime.com/');

INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (45, 4, 'Fashion & Clothes', 'H&M', 'https://hm.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.hm.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (46, 4, 'Fashion & Clothes', 'DKNY', 'https://donnakaran.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.donnakaran.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (47, 4, 'Fashion & Clothes', 'Kangol', 'https://kangol.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.kangol.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (48, 4, 'Fashion & Clothes', 'Hogan', 'https://hogan.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.hogan.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (49, 4, 'Fashion & Clothes', 'Shein', 'https://us.shein.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.shein.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (50, 4, 'Fashion & Clothes', 'Ensorings', 'https://ensorings.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.ensorings.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (51, 4, 'Fashion & Clothes', 'Asics', 'https://asics.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.asics.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (52, 4, 'Fashion & Clothes', 'Kangol', 'https://kangol.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.kangol.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (53, 4, 'Fashion & Clothes', 'Choosy', 'https://getchoosy.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.getchoosy.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (54, 4, 'Fashion & Clothes', 'Catherines', 'https://catherines.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.catherines.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (55, 4, 'Fashion & Clothes', 'Dresslily', 'https://dresslily.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.dresslily.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (56, 4, 'Fashion & Clothes', 'Bugatchi', 'https://bugatchi.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.bugatchi.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (57, 4, 'Fashion & Clothes', 'Reiss', 'https://reiss.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.reiss.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (58, 4, 'Fashion & Clothes', '525 America', 'https://525america.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.525america.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (59, 4, 'Fashion & Clothes', 'Michael Stars', 'https://michaelstars.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.michaelstars.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (60, 4, 'Fashion & Clothes', 'Shoebacca', 'https://shoebacca.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.shoebacca.com/');

INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (61, 5, 'Health & Diet', 'Canviva', 'https://canviva.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.canviva.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (62, 5, 'Health & Diet', 'Noom', 'https://noom.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.noom.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (63, 5, 'Health & Diet', 'Qnlabs', 'https://qnlabs.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.qnlabs.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (64, 5, 'Health & Diet', 'My vitamins', 'https://myvitamins.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.myvitamins.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (65, 5, 'Health & Diet', 'Nutrition53', 'https://nutrition53.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.nutrition53.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (66, 5, 'Health & Diet', 'Earth Medicine', 'https://earthmedicinehemp.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.earthmedicinehemp.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (67, 5, 'Health & Diet', 'Organic BF', 'https://organicbabyfood24.de', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.organicbabyfood24.de/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (68, 5, 'Health & Diet', 'Asquared Nutrition', 'https://asquarednutrition.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.asquarednutrition.com/');

INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (69, 6, 'Travel & Hotel', 'Booking', 'https://booking.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.booking.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (70, 6, 'Travel & Hotel', 'Trivago', 'https://trivago.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.trivago.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (71, 6, 'Travel & Hotel', 'Skyscanner', 'https://skyscanner.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.skyscanner.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (72, 6, 'Travel & Hotel', 'Expedia', 'https://expedia.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.expedia.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (73, 6, 'Travel & Hotel', 'Agoda', 'https://agoda.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.agoda.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (74, 6, 'Travel & Hotel', 'On the beach', 'https://onthebeach.co.uk', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.onthebeach.co.uk/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (75, 6, 'Travel & Hotel', 'Cheap Flights Freak', 'https://cheapflightsfreak.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.cheapflightsfreak.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (76, 6, 'Travel & Hotel', 'Kiwi', 'https://kiwi.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.kiwi.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (77, 6, 'Travel & Hotel', 'Hilton', 'https://hilton.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.hilton.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (78, 6, 'Travel & Hotel', 'Avoya Travel', 'https://avoyatravel.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.avoyatravel.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (79, 6, 'Travel & Hotel', 'Loews Hotels', 'https://loewshotels.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.loewshotels.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (80, 6, 'Travel & Hotel', 'Easy Rent Cars', 'https://qeeq.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.qeeq.com/');

INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (81, 7, 'Social Media', 'Facebook', 'https://facebook.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.facebook.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (82, 7, 'Social Media', 'Twitter', 'https://twitter.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.twitter.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (83, 7, 'Social Media', 'Instagram', 'https://instagram.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.instagram.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (84, 7, 'Social Media', 'Youtube', 'https://youtube.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.youtube.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (85, 7, 'Social Media', 'Linkedin', 'https://linkedin.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.linkedin.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (86, 7, 'Social Media', 'Snapchat', 'https://snapchat.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.snapchat.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (87, 7, 'Social Media', 'Whatsapp', 'https://whatsapp.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.whatsapp.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (88, 7, 'Social Media', 'Telegram', 'https://telegram.org', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.telegram.org/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (89, 7, 'Social Media', 'Skype', 'https://skype.com/en/', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.skype.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (90, 7, 'Social Media', 'Reddit', 'https://reddit.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.reddit.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (91, 7, 'Social Media', 'Pinterest', 'https://pinterest.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.pinterest.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (92, 7, 'Social Media', 'Flickr', 'https://flickr.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.flickr.com/');

INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (93, 8, 'Education', 'Udemy', 'https://udemy.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.udemy.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (94, 8, 'Education', 'Coursera', 'https://coursera.org', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.coursera.org/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (95, 8, 'Education', 'edx', 'https://edx.org', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.edx.org/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (96, 8, 'Education', 'Udacity', 'https://udacity.com', 'https://raw.githubusercontent.com/lateef10/OtherWebOrg/master/AllWeb/udacity.jpg');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (97, 8, 'Education', 'Mondly', 'https://mondly.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.mondly.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (98, 8, 'Education', 'Discount School', 'https://discountschoolsupply.com', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.discountschoolsupply.com/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (99, 8, 'Education', 'GCF Global', 'https://gcfglobal.org/en/', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.gcfglobal.org/');
INSERT or IGNORE INTO AllWebsite(id, CatId, CatName, WebsiteName, WebsiteURL, ImageURL) VALUES (100, 8, 'Education', 'E-learning Kids', 'https://e-learningforkids.org', 'https://s2.googleusercontent.com/s2/favicons?domain_url=https://www.e-learningforkids.org/');